CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id BIGINT NOT NULL,
    target_id BIGINT NULL,
    action_type VARCHAR(50) NOT NULL,
    action_details VARCHAR(70) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_audit_actor FOREIGN KEY (actor_id) REFERENCES useraccount(id),
    CONSTRAINT fk_audit_target FOREIGN KEY (target_id) REFERENCES useraccount(id)
);

CREATE INDEX IF NOT EXISTS idx_audit_actor ON audit_log(actor_id);
CREATE INDEX IF NOT EXISTS idx_audit_target ON audit_log(target_id);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_log(created_at);
